const DEFAULT_SERVICES = [
  {
    code: "M1001",
    name: "Shirt",
    unit: "Wash & Iron",
    price: 25,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/2503/2503380.png",
    popular: true,
    active: true,
  },
  {
    code: "M1002",
    name: "Pant",
    unit: "Wash & Iron",
    price: 35,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/862/862993.png",
    popular: true,
    active: true,
  },
  {
    code: "M1003",
    name: "Suit",
    unit: "Dry Clean",
    price: 200,
    category: "men",
    img: "https://png.pngtree.com/png-vector/20240825/ourmid/pngtree-blue-suit-with-striped-tie-clipart-illustration-png-image_13613686.png",
    popular: true,
    active: true,
  },
  {
    code: "M1004",
    name: "Blazer",
    unit: "Dry Clean",
    price: 180,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/15487/15487198.png",
    popular: true,
    active: true,
  },
  {
    code: "M1005",
    name: "Jeans",
    unit: "Wash & Iron",
    price: 40,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/5258/5258257.png",
    popular: true,
    active: true,
  },
  {
    code: "M1006",
    name: "T-Shirt",
    unit: "Wash & Iron",
    price: 20,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/512/892/892458.png",
    popular: true,
    active: true,
  },
  {
    code: "M1007",
    name: "Kurta",
    unit: "Wash & Iron",
    price: 45,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/512/9992/9992462.png",
    popular: true,
    active: true,
  },
  {
    code: "M1008",
    name: "Pajama",
    unit: "Wash & Iron",
    price: 30,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/4446/4446182.png",
    popular: true,
    active: true,
  },
  {
    code: "M1009",
    name: "Shorts",
    unit: "Wash & Iron",
    price: 25,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/3345/3345397.png",
    popular: true,
    active: true,
  },
  {
    code: "M1010",
    name: "Sweater",
    unit: "Dry Clean",
    price: 60,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/9431/9431166.png",
    popular: true,
    active: true,
  },
  {
    code: "M1011",
    name: "Jacket",
    unit: "Dry Clean",
    price: 150,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/2806/2806175.png",
    popular: true,
    active: true,
  },
  {
    code: "M1012",
    name: "Coat",
    unit: "Dry Clean",
    price: 180,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/15442/15442567.png",
    popular: true,
    active: true,
  },
  {
    code: "M1013",
    name: "Waistcoat",
    unit: "Dry Clean",
    price: 100,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/3345/3345814.png",
    popular: true,
    active: true,
  },
  {
    code: "M1014",
    name: "Dhoti",
    unit: "Wash & Iron",
    price: 40,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/8392/8392331.png",
    popular: true,
    active: true,
  },
  {
    code: "M1015",
    name: "Sherwani",
    unit: "Dry Clean",
    price: 250,
    category: "men",
    img: "https://cdn-icons-png.flaticon.com/128/16433/16433062.png",
    popular: true,
    active: true,
  },
  {
    code: "F1001",
    name: "Dress",
    unit: "Wash & Iron",
    price: 50,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/3534/3534312.png",
    popular: true,
    active: true,
  },
  {
    code: "F1002",
    name: "Skirt",
    unit: "Wash & Iron",
    price: 40,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/4507/4507761.png",
    popular: true,
    active: true,
  },
  {
    code: "F1003",
    name: "Blouse",
    unit: "Wash & Iron",
    price: 30,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/7394/7394902.png",
    popular: true,
    active: true,
  },
  {
    code: "F1004",
    name: "Saree",
    unit: "Dry Clean",
    price: 80,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/5638/5638937.png",
    popular: true,
    active: true,
  },
  {
    code: "F1005",
    name: "Jeans",
    unit: "Wash & Iron",
    price: 40,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/599/599388.png",
    popular: true,
    active: true,
  },
  {
    code: "F1006",
    name: "T-Shirt",
    unit: "Wash & Iron",
    price: 20,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/512/892/892458.png",
    popular: true,
    active: true,
  },
  {
    code: "F1007",
    name: "Salwar Kameez",
    unit: "Wash & Iron",
    price: 60,
    category: "female",
    img: "https://globalsymbols.com/uploads/production/image/imagefile/6435/14_6435_9e07011e-ad77-4054-baf1-922095b68c1a.svg",
    popular: true,
    active: true,
  },
  {
    code: "F1008",
    name: "Leggings",
    unit: "Wash & Iron",
    price: 25,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/1947/1947484.png",
    popular: true,
    active: true,
  },
  {
    code: "F1009",
    name: "Shorts",
    unit: "Wash & Iron",
    price: 25,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/12916/12916711.png",
    popular: true,
    active: true,
  },
  {
    code: "F1010",
    name: "Sweater",
    unit: "Dry Clean",
    price: 60,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/15710/15710379.png",
    popular: true,
    active: true,
  },
  {
    code: "F1011",
    name: "Jacket",
    unit: "Dry Clean",
    price: 150,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/12916/12916656.png",
    popular: true,
    active: true,
  },
  {
    code: "F1012",
    name: "Coat",
    unit: "Dry Clean",
    price: 180,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/3636/3636674.png",
    popular: true,
    active: true,
  },
  {
    code: "F1013",
    name: "Dupatta",
    unit: "Wash & Iron",
    price: 30,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/6263/6263422.png",
    popular: true,
    active: true,
  },
  {
    code: "F1014",
    name: "Lehenga",
    unit: "Dry Clean",
    price: 200,
    category: "female",
    img: "https://png.pngtree.com/png-clipart/20230917/original/pngtree-an-illustration-of-a-dress-that-is-in-ethnic-pattern-vector-png-image_12271759.png",
    popular: true,
    active: true,
  },
  {
    code: "F1015",
    name: "Gown",
    unit: "Dry Clean",
    price: 220,
    category: "female",
    img: "https://cdn-icons-png.flaticon.com/128/7590/7590205.png",
    popular: true,
    active: true,
  },
  {
    code: "K1001",
    name: "Kids Shirt",
    unit: "Wash & Iron",
    price: 15,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/4108/4108959.png",
    popular: true,
    active: true,
  },
  {
    code: "K1002",
    name: "Kids Pant",
    unit: "Wash & Iron",
    price: 20,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/8761/8761208.png",
    popular: true,
    active: true,
  },
  {
    code: "K1003",
    name: "Kids Suit",
    unit: "Dry Clean",
    price: 100,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/13943/13943895.png",
    popular: true,
    active: true,
  },
  {
    code: "K1004",
    name: "Kids Blazer",
    unit: "Dry Clean",
    price: 80,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/17303/17303411.png",
    popular: true,
    active: true,
  },
  {
    code: "K1005",
    name: "Kids Jeans",
    unit: "Wash & Iron",
    price: 30,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/8761/8761274.png",
    popular: true,
    active: true,
  },
  {
    code: "K1006",
    name: "Kids T-Shirt",
    unit: "Wash & Iron",
    price: 15,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/4108/4108959.png",
    popular: true,
    active: true,
  },
  {
    code: "K1007",
    name: "Kids Kurta",
    unit: "Wash & Iron",
    price: 25,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/9992/9992462.png",
    popular: true,
    active: true,
  },
  {
    code: "K1008",
    name: "Kids Pajama",
    unit: "Wash & Iron",
    price: 20,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/17891/17891189.png",
    popular: true,
    active: true,
  },
  {
    code: "K1009",
    name: "Kids Shorts",
    unit: "Wash & Iron",
    price: 15,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/512/8189/8189959.png",
    popular: true,
    active: true,
  },
  {
    code: "K1010",
    name: "Kids Sweater",
    unit: "Dry Clean",
    price: 50,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/15730/15730039.png",
    popular: true,
    active: true,
  },
  {
    code: "K1011",
    name: "Kids Jacket",
    unit: "Dry Clean",
    price: 120,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/8761/8761165.png",
    popular: true,
    active: true,
  },
  {
    code: "K1012",
    name: "Kids Coat",
    unit: "Dry Clean",
    price: 150,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/9338/9338587.png",
    popular: true,
    active: true,
  },
  {
    code: "K1013",
    name: "Kids Waistcoat",
    unit: "Dry Clean",
    price: 80,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/1177/1177024.png",
    popular: true,
    active: true,
  },
  {
    code: "K1014",
    name: "Kids Dhoti",
    unit: "Wash & Iron",
    price: 25,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/6669/6669282.png",
    popular: true,
    active: true,
  },
  {
    code: "K1015",
    name: "Kids Sherwani",
    unit: "Dry Clean",
    price: 180,
    category: "kids",
    img: "https://cdn-icons-png.flaticon.com/128/16433/16433027.png",
    popular: true,
    active: true,
  },
];

module.exports = { DEFAULT_SERVICES };
