export const dryCleanServices = [
  {
    id: "DC1",
    name: "Dry Clean Shirt",
    displayName: "Shirt",
    price: 80,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/2503/2503380.png",
    popular: true,
  },
  {
    id: "DC2",
    name: "Dry Clean Pant",
    displayName: "Pant / Trouser",
    price: 100,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/862/862993.png",
    popular: true,
  },
  {
    id: "DC3",
    name: "Dry Clean T-Shirt",
    displayName: "T-Shirt",
    price: 70,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/512/892/892458.png",
    popular: true,
  },
  {
    id: "DC4",
    name: "Dry Clean Jeans",
    displayName: "Jeans",
    price: 120,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/5258/5258257.png",
    popular: true,
  },
  {
    id: "DC5",
    name: "Dry Clean Kurta",
    displayName: "Kurta",
    price: 110,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/512/9992/9992462.png",
    popular: true,
  },
  {
    id: "DC6",
    name: "Dry Clean Safari Suit",
    displayName: "Safari Suit",
    price: 180,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/3345/3345814.png",
    popular: true,
  },
  {
    id: "DC7",
    name: "Dry Clean Blazer",
    displayName: "Blazer",
    price: 250,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/15487/15487198.png",
    popular: true,
  },
  {
    id: "DC8",
    name: "Dry Clean Coat",
    displayName: "Coat",
    price: 220,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/15442/15442567.png",
    popular: true,
  },
  {
    id: "DC9",
    name: "Dry Clean Sweater",
    displayName: "Sweater",
    price: 130,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/9431/9431166.png",
    popular: true,
  },
  {
    id: "DC10",
    name: "Dry Clean Shawl",
    displayName: "Shawl",
    price: 160,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/6263/6263422.png",
    popular: true,
  },
  {
    id: "DC11",
    name: "Leather Jacket Care",
    displayName: "Leather Jacket",
    price: 500,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/2806/2806175.png",
    popular: true,
  },
  {
    id: "DC12",
    name: "Leather Bag Care",
    displayName: "Leather Bag",
    price: 350,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/3081/3081559.png",
    popular: true,
  },
  {
    id: "DC13",
    name: "Leather Belt Care",
    displayName: "Leather Belt",
    price: 150,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/599/599402.png",
    popular: false,
  },
  {
    id: "DC14",
    name: "Woolen Coat Care",
    displayName: "Woolen Coat",
    price: 280,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/3636/3636674.png",
    popular: true,
  },
  {
    id: "DC15",
    name: "Pashmina Shawl Care",
    displayName: "Pashmina Shawl",
    price: 350,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/6263/6263422.png",
    popular: true,
  },
  {
    id: "DC16",
    name: "Silk Saree Care",
    displayName: "Silk Saree",
    price: 250,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/5638/5638937.png",
    popular: true,
  },
  {
    id: "DC17",
    name: "Embroidery Dress Care",
    displayName: "Embroidery Dress",
    price: 450,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/3534/3534312.png",
    popular: true,
  },
  {
    id: "DC18",
    name: "Boots Care",
    displayName: "Boots",
    price: 250,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/2589/2589874.png",
    popular: false,
  },
  {
    id: "DC19",
    name: "Delicate Blanket Care",
    displayName: "Delicate Blanket",
    price: 300,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/2936/2936886.png",
    popular: false,
  },
  {
    id: "DC20",
    name: "Premium Suit Care",
    displayName: "Premium Suit",
    price: 450,
    unit: "Dry Clean",
    category: "dryclean",
    img: "https://cdn-icons-png.flaticon.com/128/15487/15487148.png",
    popular: true,
  },
];
