export const slides = [
    {
        id: 1,
        title: "Professional Laundry Service",
        img: "https://images.pexels.com/photos/8774568/pexels-photo-8774568.jpeg",
    },
    {
        id: 2,
        title: "Fast & Fresh Washing",
        img: "https://images.pexels.com/photos/6466227/pexels-photo-6466227.jpeg",
    },
    {
        id: 3,
        title: "Doorstep Pickup & Delivery",
        img: "https://images.pexels.com/photos/6169000/pexels-photo-6169000.jpeg",
    },
    {
        id: 4,
        title: "Perfectly Pressed Clothes",
        img: "https://img.freepik.com/premium-photo/portrait-smiling-young-woman-holding-gift-against-yellow-background_1048944-22575019.jpg?ga=GA1.1.1817863647.1759326080&semt=ais_incoming&w=740&q=80",
    },
];

// 🧺 Service category cards
export const cards = [
    {
        id: 1,
        name: "Shirt",
        price: 25,
        unit: "Wash & Iron",
        img: "https://cdn-icons-png.flaticon.com/128/2503/2503380.png",
        popular: true,
    },

    {
        id: 2,
        name: "Pant",
        price: 35,
        unit: "Wash & Iron",
        img: "https://cdn-icons-png.flaticon.com/128/862/862993.png",
        popular: true,
    },
    {
        id: 3,
        name: "Suit",
        price: 200,
        unit: "Dry Clean",
        img: "https://png.pngtree.com/png-vector/20240825/ourmid/pngtree-blue-suit-with-striped-tie-clipart-illustration-png-image_13613686.png",
        popular: true,
    },
    {
        id: 4,
        name: "Blazer",
        price: 180,
        unit: "Dry Clean",
        img: "https://cdn-icons-png.flaticon.com/128/15487/15487198.png",
        popular: true,
    },

    {
        id: "F1",
        name: "Dress",
        price: 50,
        unit: "Wash & Iron",
        img: "https://cdn-icons-png.flaticon.com/128/3534/3534312.png",
        popular: true,
    },
    {
        id: "F2",
        name: "Skirt",
        price: 40,
        unit: "Wash & Iron",
        img: "https://cdn-icons-png.flaticon.com/128/4507/4507761.png",
        popular: true,
    },
    {
        id: "F3",
        name: "Blouse",
        price: 30,
        unit: "Wash & Iron",
        img: "https://cdn-icons-png.flaticon.com/128/7394/7394902.png",
        popular: true,
    },
    {
        id: "F4",
        name: "Saree",
        price: 80,
        unit: "Dry Clean",
        img: "https://cdn-icons-png.flaticon.com/128/5638/5638937.png",
        popular: true,
    },
    {
        id: "K1",
        name: "Kids Shirt",
        price: 15,
        unit: "Wash & Iron",
        img: "https://cdn-icons-png.flaticon.com/128/4108/4108959.png",
        popular: true,
    },
    {
        id: "K2",
        name: "Kids Pant",
        price: 20,
        unit: "Wash & Iron",
        img: "https://cdn-icons-png.flaticon.com/128/8761/8761208.png",
        popular: true,
    },
    {
        id: "K3",
        name: "Kids Suit",
        price: 100,
        unit: "Dry Clean",
        img: "https://cdn-icons-png.flaticon.com/128/13943/13943895.png",
        popular: true,
    },
    {
        id: "K4",
        name: "Kids Blazer",
        price: 80,
        unit: "Dry Clean",
        img: "https://cdn-icons-png.flaticon.com/128/17303/17303411.png",
        popular: true,
    },
];

// 🧼 Dry Clean Rates section
export const dryCleanPlans = [
    {
        id: 1,
        title: "Signature Dry Clean",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4gBB3fD87Nj9kRiOWbYUEcgBqclr5HswQFg&s",
        description: "Premium fabric-friendly dry cleaning.",
        price: "₹199",
        subtitle: "per item",
        features: [
            "Premium Care",
            "Fabric Safety",
            "No Shrinkage",
        ],

        rateList: [
            { item: "Shirt", price: "₹80" },
            { item: "Pant / Trouser", price: "₹100" },
            { item: "T-Shirt", price: "₹70" },
            { item: "Jeans", price: "₹120" },
            { item: "Kurta", price: "₹110" },
            { item: "Safari Suit", price: "₹180" },
            { item: "Blazer", price: "₹250" },
            { item: "Coat", price: "₹220" },
            { item: "Sweater", price: "₹130" },
            { item: "Shawl", price: "₹160" },
        ],
    },

    // {
    //     id: 2,
    //     title: "Organic Dry Clean",
    //     img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmg8AA-3v4H50zTxfPDu_hwYLVVI8rNTDVzw&s",
    //     description: "Eco-friendly allergy-safe organic cleaning.",
    //     price: "₹249",
    //     subtitle: "per item",
    //     features: [
    //         "100% Chemical Free",
    //         "Eco Safe",
    //         "Skin Friendly",
    //     ],

    //     rateList: [
    //         { item: "Cotton Shirt", price: "₹90" },
    //         { item: "Linen Shirt", price: "₹120" },
    //         { item: "Organic Kurta", price: "₹140" },
    //         { item: "Soft Saree", price: "₹180" },
    //         { item: "Soft Top", price: "₹95" },
    //         { item: "Kids Dress", price: "₹70" },
    //         { item: "Dupatta", price: "₹60" },
    //         { item: "Skirt", price: "₹110" },
    //         { item: "Plazzo", price: "₹90" },
    //         { item: "Organic Woolen", price: "₹160" },
    //     ],
    // },
    {
        id: 3,
        title: "Leather & Delicate",
        img: "https://thumbs.dreamstime.com/b/leather-dry-cleaning-icon-simple-illustration-laundry-collection-creative-web-design-templates-infographics-more-181025829.jpg",
        description: "Leather, woolens & premium fabrics expert care.",
        price: "₹399",
        subtitle: "per item",
        features: [
            "Leather Conditioning",
            "Soft Finish",
            "Hand Processed",
        ],

        rateList: [
            { item: "Leather Jacket", price: "₹500" },
            { item: "Leather Bag", price: "₹350" },
            { item: "Leather Belt", price: "₹150" },
            { item: "Woolen Coat", price: "₹280" },
            { item: "Pashmina Shawl", price: "₹350" },
            { item: "Silk Saree", price: "₹250" },
            { item: "Embroidery Dress", price: "₹450" },
            { item: "Boots", price: "₹250" },
            { item: "Delicate Blanket", price: "₹300" },
            { item: "Premium Suit", price: "₹450" },
        ],
    }

];

export const washRates = [
    {
        id: 1,
        title: "Shirt / T-Shirt",
        price: "₹40",
        priceValue: 40,
        unit: "per piece",
        emoji: "👕",
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=example4",
        description: "Quick wash + light iron — fresh and wearable same week.",
        turnaround: "24-48 hrs",
        features: ["Light ironing", "Color-safe detergent", "Quick turnaround"],
    },
    {
        id: 2,
        title: "Trousers / Jeans",
        price: "₹50",
        priceValue: 50,
        unit: "per piece",
        emoji: "👖",
        image: "https://images.unsplash.com/photo-1533850595623-2f44e0c4f1b6?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=example5",
        description: "Sturdy-cleaning that keeps shape & color intact.",
        turnaround: "24-48 hrs",
        features: ["Stain pre-treatment", "Shape care"],
    },
    {
        id: 3,
        title: "Bedsheet (Single)",
        price: "₹80",
        priceValue: 80,
        unit: "per piece",
        emoji: "🛏️",
        image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=example6",
        description: "Deep clean, extra rinse for a soft, hygienic finish.",
        turnaround: "48-72 hrs",
        features: ["Sanitizing wash", "Extra rinse"],
    },
    {
        id: 4,
        title: "Curtains (per piece)",
        price: "₹120",
        priceValue: 120,
        unit: "per piece",
        emoji: "🪟",
        image: "https://images.unsplash.com/photo-1598300051001-2f5b5b3f7c9d?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=example7",
        description: "Delicate handling to prevent shrinkage and preserve texture.",
        turnaround: "3-5 days",
        features: ["Delicate cycle", "Steam finish"],
    },
    {
        id: 5,
        title: "Blanket",
        price: "₹150",
        priceValue: 150,
        unit: "per piece",
        emoji: "🛏️",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=example8",
        description: "Deep-clean for heavy items, gentle drying to avoid damage.",
        turnaround: "3-5 days",
        features: ["Deep cleaning", "Careful drying"],
    },
    {
        id: 6,
        title: "Saree",
        price: "₹90",
        priceValue: 90,
        unit: "per piece",
        emoji: "👗",
        image: "https://images.unsplash.com/photo-1520975912802-6f2b5fbd7d8b?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=example9",
        description: "Handled with special care; hand-finish available for delicate sarees.",
        turnaround: "48-72 hrs",
        features: ["Hand-finish option", "Color protection"],
    },
];

// export const prepaidPlans = [

//     {
//         id: 1,
//         title: "Silver Boost — ₹500",
//         price: "₹500",
//         priceValue: 500,
//         benefit: "Save ₹50",
//         desc: "Prepaid credit + small perks — best for occasional users.",
//         image: "https://images.unsplash.com/photo-1556742400-b5b512f50d20?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=example10",
//         features: ["₹550 credit", "Priority pickup (standard)", "1 free stain treat"],
//         validity: "3 months",
//         tag: "Starter",
//     },
//     {
//         id: 2,
//         title: "Gold Care — ₹1000",
//         price: "₹1000",
//         priceValue: 1000,
//         benefit: "Save ₹150",
//         desc: "Popular — best balance of savings + perks for families.",
//         image: "https://images.unsplash.com/photo-1545239708-8fdb6c12b5f6?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=example11",
//         features: ["₹1150 credit", "Priority pickup", "Exclusive offers", "2 free stain treats"],
//         validity: "6 months",
//         tag: "Popular",
//     },
//     {
//         id: 3,
//         title: "Platinum Luxe — ₹2000",
//         price: "₹2000",
//         priceValue: 2000,
//         benefit: "Save ₹400",
//         desc: "For regular users — max savings, premium pickup & delivery windows.",
//         image: "https://images.unsplash.com/photo-1544161515-4ab19145b803?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=example12",
//         features: ["₹2400 credit", "Express pickup & delivery", "Priority queue", "Free repairs (1)"],
//         validity: "12 months",
//         tag: "Luxe",
//     },
// ];
