export const kidsservices = [
    {
         id: "K1",
         name: "Kids Shirt",
         price: 15,
         unit: "Wash & Iron",
         img: "https://cdn-icons-png.flaticon.com/128/4108/4108959.png",
         popular: true, },
    {
         id: "K2",
         name: "Kids Pant",
         price: 20,
         unit: "Wash & Iron",
         img: "https://cdn-icons-png.flaticon.com/128/8761/8761208.png",
         popular: true, },
    {
         id: "K3",
         name: "Kids Suit",
         price: 100,
         unit: "Dry Clean",
         img: "https://cdn-icons-png.flaticon.com/128/13943/13943895.png",
         popular: true, },
    {
         id: "K4",
         name: "Kids Blazer",
         price: 80,
         unit: "Dry Clean",
         img: "https://cdn-icons-png.flaticon.com/128/17303/17303411.png",
         popular: true, },
    {
         id: "K5",
         name: "Kids Jeans",
         price: 30,
         unit: "Wash & Iron",
         img: "https://cdn-icons-png.flaticon.com/128/8761/8761274.png",
         popular: true, },
    {
         id: "K6",
         name: "Kids T-Shirt",
         price: 15,
         unit: "Wash & Iron",
         img: "https://cdn-icons-png.flaticon.com/128/4108/4108959.png",
         popular: true, },
    {
         id: "K7",
         name: "Kids Kurta",
         price: 25,
         unit: "Wash & Iron",
         img: "https://cdn-icons-png.flaticon.com/128/9992/9992462.png",
         popular: true, },
    {
         id: "K8",
         name: "Kids Pajama",
         price: 20,
         unit: "Wash & Iron",
         img: "https://cdn-icons-png.flaticon.com/128/17891/17891189.png",
         popular: true, },
    {
         id: "K9",
         name: "Kids Shorts",
         price: 15,
         unit: "Wash & Iron",
         img: "https://cdn-icons-png.flaticon.com/512/8189/8189959.png",
         popular: true, },
    {
         id: "K10",
         name: "Kids Sweater",
         price: 50,
         unit: "Dry Clean",
         img: "https://cdn-icons-png.flaticon.com/128/15730/15730039.png",
         popular: true, },
    {
         id: "K11",
         name: "Kids Jacket",
         price: 120,
         unit: "Dry Clean",
         img: "https://cdn-icons-png.flaticon.com/128/8761/8761165.png",
         popular: true, },
    {
         id: "K12",
         name: "Kids Coat",
         price: 150,
         unit: "Dry Clean",
         img: "https://cdn-icons-png.flaticon.com/128/9338/9338587.png",
         popular: true, },
    {
         id: "K13",
         name: "Kids Waistcoat",
         price: 80,
         unit: "Dry Clean",
         img: "https://cdn-icons-png.flaticon.com/128/1177/1177024.png",
         popular: true, },
    {
         id: "K14",
         name: "Kids Dhoti",
         price: 25,
         unit: "Wash & Iron",
         img: "https://cdn-icons-png.flaticon.com/128/6669/6669282.png",
         popular: true, },
    {
         id: "K15",
         name: "Kids Sherwani",
         price: 180,
         unit: "Dry Clean",
         img: "https://cdn-icons-png.flaticon.com/128/16433/16433027.png",
         popular: true, },
];